### ISSUE TITLE
License is not defined

### ISSUE THREAD

**Issue by lmiori92** [ZoetropeImaging/Arduino-SuperSerial#3]
Hi,

I'm interested in using the library first and then also potentially contributing to the project as I have some ideas.
The thing that's stopping me is the licensing terms which seem not to be documented anywhere.
The project shall really define a license or else the general rule applies (see: [https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license](url)

Is the default licensing applied here intentionally?

Thank you

**Comment by benhowes** [comment]
Please do what ever you want with this project, commercial or otherwise!

I'll add a license

**Comment by benhowes** [comment]
I've added an MIT license. Have fun!

**Comment by lmiori92** [comment]
Nice, thank you!
